### ISSUE TITLE
klikken op 'Objecten' in breadcrumb geeft error

### ISSUE THREAD

**Issue by roxannewyns** [libis/Aezel-omeka#11]
![image](https://user-images.githubusercontent.com/3798589/28263114-e9cfa9e0-6ae5-11e7-9374-d061072cdc9f.png)

![image](https://user-images.githubusercontent.com/3798589/28263131-f969aa2c-6ae5-11e7-8452-71d189d0fe49.png)

**Comment by JorisLambrechts** [comment]
fixed na herindexeren
