### ISSUE TITLE
links toevoegen

### ISSUE THREAD

**Issue by roxannewyns** [libis/Aezel-omeka#20]
In alle subnavigaties staat 'Onze collectie' bovenaan. Nu wil de partner overal een link toevoegen naar items van een bepaald type.  

/omeka/hoe
/omeka/solr-search?q=&facet=itemtype:"Hoe"

/omeka/projecten
/omeka/solr-search?q=&facet=itemtype:"Projecten"

/omeka/samenwerking
/omeka/solr-search?q=&facet=itemtype:"Samenwerking"

/omeka/aezel
/omeka/solr-search?q=&facet=itemtype:"Aezel"

/omeka/info
/omeka/solr-search?q=&facet=itemtype:"Info"

/omeka/doel
/omeka/solr-search?q=&facet=itemtype:"Doel"

/omeka/vrijwilligers
/omeka/solr-search?q=&facet=itemtype:"Vrijwilligers"

![image](https://user-images.githubusercontent.com/3798589/28514665-29689b46-705b-11e7-9634-38cefd29bcbf.png)

**Comment by JorisLambrechts** [comment]
Geld dit ook voor de onderliggende paginas (child-pages van Hoe bijvoorbeeld)?

**Comment by roxannewyns** [comment]
had nog niet gezien dat 'onze collectie' daar ook verscheen. Nee, voorlopig niet.
