### ISSUE TITLE
Nieuws in submenu weghalen, behalve bij Doel

### ISSUE THREAD

**Issue by roxannewyns** [libis/Aezel-omeka#22]
Nieuws (link naar items van het type nieuws) mag enkel verschijnen onder Doel, en moet verwijderd worden onder alle andere pagina's. Kan dit ook zo gedaan worden dat het niet verschijnt onder nieuwe toevoegingen?

![image](https://user-images.githubusercontent.com/3798589/30069193-4c8b8d0a-9260-11e7-9ede-5714e50441bd.png)

**Comment by JorisLambrechts** [comment]
wat bedoel je met nieuwe toevoegingen?

**Comment by roxannewyns** [comment]
Stel dat je ene nieuwe simple page als hoofdpagina zou toevoegen, verschijnt nieuws dan weer in de subnavigatie?
