### ISSUE TITLE
Bekijk online + link toevoegen

### ISSUE THREAD

**Issue by roxannewyns** [libis/Aezel-omeka#6]
De partner wil op deze site een overzicht van de mogelijke thema's geven in bv. geoexplorer. 
In dc:references (kan ook een ander veld zijn indien beter) komt de link naar de externe applicatie te staan. Bezoekers die de link aanklikken worden dan doorverwezen naar de geoexplorer front-end thema demografie.

Kan je References gewoon laten verschijnen als 'Bekijk online' met de link erachter. 
![image](https://user-images.githubusercontent.com/3798589/27550463-12675c82-5aa0-11e7-8abf-4922d197f9ad.png)

**Comment by JorisLambrechts** [comment]
Welke metadata moet er allemaal staan (voorlopig wordt alles getoond)

**Comment by roxannewyns** [comment]
Alleen references misschien verbergen omdat we dit gebruiken voor bekijk online. Al de rest mag blijven staan.
