### ISSUE TITLE
kleur & logo per item type

### ISSUE THREAD

**Issue by roxannewyns** [libis/Aezel-omeka#8]
item type 'Kaart' = blauwe kleur & bijpassend logo /omeka/waar
item type 'Kaart historie' = oranje kleur & bijpassend logo /omeka/wanneer
item type 'Erfgoed website' = rode kleur & bijpassend logo /omeka/wat
item type 'Stamboom' = groene kleur & bijpassend logo /omeka/wie

**Comment by JorisLambrechts** [comment]
https://github.com/libis/Aezel-omeka/commit/97469cf33aeef08fd85ea0e0fa3fb548604f9ea1

**Comment by roxannewyns** [comment]
Kaart historie zou oranje kleur moeten volgen, maar is rood.
Kan je dit nog toevoegen. Andere zijn ok. 

![image](https://user-images.githubusercontent.com/3798589/28203900-fb4c8b00-687b-11e7-8ec2-7bee25fc53db.png)

**Resultaat**
![image](https://user-images.githubusercontent.com/3798589/28203869-d2433c0e-687b-11e7-80df-25000027ce54.png)
