### ISSUE TITLE
Doorlinken naar item browe page per item type

### ISSUE THREAD

**Issue by roxannewyns** [libis/Aezel-omeka#9]
'Stamboom' in subnavigatie moet doorlinken naar item browse page beperkt tot item type 'Stamboom'
'Kaart Historie' in subnavigatie moet doorlinken naar item browse page beperkt tot item type 'Kaart historie'
'Landkaart' in subnavigatie moet doorlinken naar item browse page beperkt tot item type 'Kaart'
'Websites Erfgoed' in subnavigatie moet doorlinken naar item browse page beperkt tot item type 'Erfgoed website'

![image](https://user-images.githubusercontent.com/3798589/27576777-7fae06c8-5b1e-11e7-86d2-06d4d3258717.png)

**Comment by JorisLambrechts** [comment]
de link verschijnt onderaan (bovenaan kan ook), omdat ik hem niet tussen de andere 'simple page' links kan zetten
